export const VARS = {
	API_PORT: process.env.API_PORT || 5005,
	API_SERVER_URL: process.env.API_SERVER_URL || '',
	API_DB_HOST: process.env.API_DB_HOST || 'localhost',
	API_DB_PORT: process.env.API_DB_PORT || 5432,
	API_DB_USER: process.env.API_DB_USER || 'postgres',
	API_DB_PASS: process.env.API_DB_PASS || 'root',
	API_DB_NAME: process.env.API_DB_NAME || 'hoteldb',
	API_DB_DIALECT: process.env.API_DB_DIALECT || 'postgres',
	API_SECRET_WORD: process.env.API_SECRET_WORD || 'secret_word',
	API_ADMIN_USERNAME: process.env.API_ADMIN_USERNAME || 'Admin username',
	API_ADMIN_PASSWORD: process.env.API_ADMIN_PASSWORD || 'Admin password',
	API_ADMIN_EMAIL: process.env.API_ADMIN_EMAIL || 'admin@sagih.com',
	API_EMAIL_USER: process.env.API_EMAIL_USER || '',
	API_EMAIL_PWD: process.env.API_EMAIL_PWD || '',
	API_EMAIL_KEY: process.env.API_EMAIL_KEY || '',
	MAIL_HOST: process.env.MAIL_HOST || '',
	MAIL_PORT: process.env.MAIL_PORT || 0,
	AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME || '',
	AWS_BUCKET_REGION: process.env.AWS_BUCKET_REGION || '',
	AWS_PUBLIC_KEY: process.env.AWS_PUBLIC_KEY || '',
	AWS_SECRET_KEY: process.env.AWS_SECRET_KEY || '',
};
